services:
  db:
    image: postgres:15
    container_name: ad-finder-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: ad-finder-redis
    restart: always
    networks:
      - app-network
    ports:
      - "6380:6379"

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
